"""Gradio interface for BlueWirks App Builder.

This script defines the user interface for generating full‑stack
application scaffolds and deploying them to various hosting
providers. It exposes a simple wizard where users describe their
idea, choose a template (Streamlit, React, or FastAPI), optionally
add tags/metadata, and then download the generated scaffold. Users
can also deploy the backend to Hugging Face Spaces or Render and
deploy the UI to Vercel from within the same interface.

The underlying generation and deployment logic lives in
``generator.py``. See that module for details on how scaffolds are
created and how deployments are performed (stubs for Render and
Vercel are provided as examples).
"""

import os
from typing import Optional
import gradio as gr
from generator import (
    generate_scaffold,
    write_zip,
    deploy_to_hf,
    deploy_to_render,
    deploy_ui_to_vercel,
)


def build_app(
    user_prompt: str,
    template: str,
    tags: str,
    blueprint: str,
    languages: str,
    theme: str,
    include_db: bool,
    include_deployment: bool,
    csv_file: Optional[str],
    schema_desc: str,
):
    """Generate the scaffold and return both the text and a zip file path.

    This function orchestrates the generation by collecting all user inputs,
    including optional blueprint selections, languages for i18n, theme
    preferences, toggles for database integration and deployment scripts, and
    a CSV preview or schema description. It reads the header of the
    uploaded CSV if present and passes all parameters to ``generate_scaffold``.
    The resulting scaffold text and a zipped archive containing README,
    configuration files, and optional extras are returned.

    Args:
        user_prompt: Description of the app the user wants to build.
        template: Chosen template (Streamlit, React, or FastAPI).
        tags: Optional comma‑separated tags for metadata.
        blueprint: Selected blueprint (e.g. chatbot engine or CRUD admin).
        languages: Comma‑separated list of languages for internationalization.
        theme: Chosen theme or brand.
        include_db: Whether to include database configuration.
        include_deployment: Whether to include deployment scripts for AWS/GCP.
        csv_file: Path to an uploaded CSV file; may be None.
        schema_desc: Optional text describing a data schema.

    Returns:
        tuple[str, str]: The generated scaffold text and the path to the
        created zip file.
    """
    # Prepare CSV preview if a file was uploaded
    csv_preview = ""
    if csv_file:
        try:
            import csv

            # csv_file comes from gr.File as a TemporaryUploadedFile; open via path
            with open(csv_file, "r", newline="") as f:
                reader = csv.reader(f)
                header = next(reader, [])
                csv_preview = ", ".join(header)
        except Exception:
            csv_preview = ""

    scaffold = generate_scaffold(
        user_prompt,
        template=template,
        tags=tags,
        blueprint=blueprint,
        languages=languages,
        theme=theme,
        include_db=include_db,
        include_deployment=include_deployment,
        csv_preview=csv_preview,
        schema_desc=schema_desc,
    )
    zip_path = write_zip(
        scaffold,
        tags=tags,
        blueprint=blueprint,
        languages=languages,
        theme=theme,
        include_db=include_db,
        include_deployment=include_deployment,
    )
    return scaffold, zip_path


def handle_deploy_backend(
    scaffold_zip: str,
    backend_target: str,
    space_name: str,
    hf_token: str,
    username: str,
    render_service: str,
    render_api_key: str,
) -> str:
    """Deploy the backend based on the chosen target.

    Depending on the ``backend_target`` parameter this function routes
    the deployment to either Hugging Face Spaces or Render. Because
    deployments typically require a directory of code rather than a
    zip file, this function extracts the parent directory of the
    provided zip file and passes that to the deployment functions.

    Args:
        scaffold_zip (str): Path to the scaffold zip file generated by
            ``write_zip``.
        backend_target (str): Either ``HF Spaces`` or ``Render``.
        space_name (str): Name of the Space (when deploying to HF).
        hf_token (str): Hugging Face access token with write permission.
        username (str): Hugging Face username.
        render_service (str): Name of the service on Render (when deploying).
        render_api_key (str): API key for Render.

    Returns:
        str: The URL of the deployed backend or an error message.
    """
    try:
        # Determine the directory containing the scaffold zip. In a real
        # implementation you would extract the zip to a temp folder and
        # deploy that folder. Here we simply use the parent directory.
        scaffold_dir = os.path.dirname(scaffold_zip)
        if backend_target == "HF Spaces":
            # Only deploy if all necessary fields are provided
            if not (space_name and hf_token and username):
                return "Missing fields: space_name, hf_token, and username are required for HF deployment."
            return deploy_to_hf(scaffold_dir, space_name, hf_token, username)
        elif backend_target == "Render":
            if not (render_service and render_api_key):
                return "Missing fields: render_service and render_api_key are required for Render deployment."
            return deploy_to_render(scaffold_dir, render_service, render_api_key)
        else:
            return f"Unsupported deployment target: {backend_target}"
    except Exception as e:
        return f"Deployment failed: {e}"


def handle_deploy_ui(scaffold_zip: str, project_name: str, vercel_token: str) -> str:
    """Deploy the frontend/UI to Vercel.

    Args:
        scaffold_zip (str): Path to the scaffold zip file.
        project_name (str): Name of the Vercel project to create.
        vercel_token (str): Vercel personal token with write access.

    Returns:
        str: The URL of the deployed UI or an error message.
    """
    try:
        if not (project_name and vercel_token):
            return "Missing fields: project_name and vercel_token are required for Vercel deployment."
        scaffold_dir = os.path.dirname(scaffold_zip)
        return deploy_ui_to_vercel(scaffold_dir, project_name, vercel_token)
    except Exception as e:
        return f"Deployment failed: {e}"


with gr.Blocks(title="BlueWirks App Builder") as demo:
    # Introduction
    gr.Markdown("## Describe, choose a template, and build your app!")

    with gr.Row():
        prompt = gr.Textbox(
            label="Describe your app idea",
            placeholder="An app that turns voice notes into haikus",
            lines=3,
        )
        template = gr.Dropdown(
            label="Choose a template",
            choices=["Streamlit", "React", "FastAPI"],
            value="Streamlit",
        )
    # Additional generation options
    tags = gr.Textbox(
        label="Tags / metadata (optional)",
        placeholder="e.g. productivity, voice",
    )
    blueprint_select = gr.Dropdown(
        label="Select a blueprint (optional)",
        choices=[
            "",
            "Chatbot engine",
            "CRUD admin app builder",
            "Analytics dashboard builder",
            "Authentication boilerplate builder",
        ],
        value="",
    )
    with gr.Row():
        languages_input = gr.Textbox(
            label="Languages (comma‑separated)",
            placeholder="e.g. English, Spanish, French",
        )
        theme_select = gr.Dropdown(
            label="Theme", choices=["Default", "Light", "Dark", "Solarized"], value="Default"
        )
    with gr.Row():
        include_db_checkbox = gr.Checkbox(label="Include DB integration", value=False)
        include_deployment_checkbox = gr.Checkbox(
            label="Include AWS/GCP deployment scripts", value=False
        )
    with gr.Row():
        csv_upload = gr.File(
            label="Upload CSV (optional)",
            file_types=[".csv"],
        )
        schema_input = gr.Textbox(
            label="Describe a schema (optional)",
            placeholder="e.g. name:string, age:int, email:string",
        )

    generate_btn = gr.Button("Generate Scaffold")
    scaffold_out = gr.Textbox(
        label="Generated Scaffold", lines=20, interactive=False
    )
    download_out = gr.File(label="Download Scaffold (.zip)")

    generate_btn.click(
        fn=build_app,
        inputs=[
            prompt,
            template,
            tags,
            blueprint_select,
            languages_input,
            theme_select,
            include_db_checkbox,
            include_deployment_checkbox,
            csv_upload,
            schema_input,
        ],
        outputs=[scaffold_out, download_out],
    )

    # Backend deployment section
    gr.Markdown("## Deploy your backend")
    backend_target = gr.Dropdown(
        label="Backend deployment target",
        choices=["HF Spaces", "Render"],
        value="HF Spaces",
    )
    with gr.Row():
        space_name = gr.Textbox(label="HF Space name", placeholder="my-cool-app")
        username = gr.Textbox(label="HF Username", placeholder="huggingface-user")
    hf_token = gr.Textbox(
        label="HF Access Token",
        type="password",
        placeholder="hf_...",
    )
    with gr.Row():
        render_service = gr.Textbox(label="Render service name", placeholder="my-render-service")
        render_api_key = gr.Textbox(
            label="Render API key", type="password", placeholder="render_api_key"
        )
    deploy_backend_btn = gr.Button("Deploy Backend")
    deploy_backend_link = gr.Textbox(
        label="Backend Deployment Link", interactive=False
    )

    deploy_backend_btn.click(
        fn=handle_deploy_backend,
        inputs=[
            download_out,
            backend_target,
            space_name,
            hf_token,
            username,
            render_service,
            render_api_key,
        ],
        outputs=[deploy_backend_link],
    )

    # UI deployment section
    gr.Markdown("## Deploy your UI to Vercel")
    with gr.Row():
        project_name = gr.Textbox(
            label="Vercel project name", placeholder="my-vercel-app"
        )
        vercel_token = gr.Textbox(
            label="Vercel token",
            type="password",
            placeholder="vercel_token",
        )
    deploy_ui_btn = gr.Button("Deploy UI")
    deploy_ui_link = gr.Textbox(label="UI Deployment Link", interactive=False)

    deploy_ui_btn.click(
        fn=handle_deploy_ui,
        inputs=[download_out, project_name, vercel_token],
        outputs=[deploy_ui_link],
    )

if __name__ == "__main__":
    demo.launch()